version: 0.4.9-{build}
environment:
  matrix:
  - TOOLSET: vs2015

os: Visual Studio 2015

shallow_clone: true

matrix:
  fast_finish: true

install:
  # Download Premake
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha11/premake-5.0.0-alpha11-windows.zip' 'premake.zip'

  # Extract it in-place; premake5.exe is at the top level.
  - 7z x premake.zip

  # Generate solution files using premake.
  - premake5.exe %TOOLSET%

configuration:
  - Debug
  - Release

build:
  project: .build/$(TOOLSET)/clink.sln

artifacts:
  - path: .build\$(TOOLSET)\bin\$(configuration)\
    type: zip
    name: clink_$(APPVEYOR_BUILD_VERSION)

  # - path: clink_0.4.9-{build}_pdb.zip
  #   name: clink_0.4.9-{build}_pdb.zip

  # - path: clink_0.4.9-{build}_setup.exe
  #   name: clink_0.4.9-{build}_setup.exe
